# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read_csv()` and explore the different options available, especially the `sep` parameter.

In [ ]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user', sep = "|")

print("Les 5 dernières lignes :")
print(df.iloc[-5:])

print("\nLes 5 premières lignes :")
print(df.iloc[:5])

print("\nType de chaque colonne :")
print(df.dtypes)

Les 5 dernières lignes :
       1  24  M     technician  85711
937  939  26  F        student  33319
938  940  32  M  administrator  02215
939  941  20  M        student  97229
940  942  48  F      librarian  78209
941  943  22  M        student  77841

Les 5 premières lignes :
   1  24  M  technician  85711
0  2  53  F       other  94043
1  3  23  M      writer  32067
2  4  24  M  technician  43537
3  5  33  F       other  15213
4  6  42  M   executive  98101

Type de chaque colonne :
1              int64
24             int64
M             object
technician    object
85711         object
dtype: object

# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv', sep = ",")
print("\nLes 5 premières lignes :")
df.iloc[:10]

Les 5 premières lignes :

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe

Set the "country" column as the index for the dataframe, using `set_index` method.

In [ ]:
df.set_index('country', inplace=True)

print("\nDataFrame après changement d'index :")
df.head()

DataFrame après changement d'index :

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa

# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)

In [ ]:
zimbabwe_data = df.loc['Zimbabwe']

print("Valeurs pour Zimbabwe :")
zimbabwe_data

Valeurs pour Zimbabwe :

beer_servings                       64
spirit_servings                     18
wine_servings                        4
total_litres_of_pure_alcohol       4.7
continent                       Africa
Name: Zimbabwe, dtype: object

# Mision 4

Display only the "continent" column value for the country **Zimbabwe**.

In [ ]:
zimbabwe_data = df.loc['Zimbabwe','continent']

print("Le continent du Zimbabwe :")
zimbabwe_data

Le continent du Zimbabwe :

'Africa'

# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))

In [ ]:
# Setting column names directly when reading the file
column_names = ['Colonne1', 'Colonne2', 'Colonne3', 'Colonne4', 'Colonne5', 'Colonne6']
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv', sep = ",", names=column_names, header=None)
print(df.head())

#Editing after creating the dataframe
df2 = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv', sep = ",")

new_column_names = ['ColonneA', 'ColonneB', 'ColonneC', 'ColonneD', 'ColonneE']
df2.columns = new_column_names
df2.head()

      Colonne1         Colonne2        Colonne3 Colonne4         Colonne5  \
0         City  Colors Reported  Shape Reported    State             Time
1       Ithaca              NaN        TRIANGLE       NY   6/1/1930 22:00
2  Willingboro              NaN           OTHER       NJ  6/30/1930 20:00
3      Holyoke              NaN            OVAL       CO  2/15/1931 14:00
4      Abilene              NaN            DISK       KS   6/1/1931 13:00

   Colonne6
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN

               ColonneA ColonneB  ColonneC ColonneD         ColonneE
0                Ithaca      NaN  TRIANGLE       NY   6/1/1930 22:00
1           Willingboro      NaN     OTHER       NJ  6/30/1930 20:00
2               Holyoke      NaN      OVAL       CO  2/15/1931 14:00
3               Abilene      NaN      DISK       KS   6/1/1931 13:00
4  New York Worlds Fair      NaN     LIGHT       NY  4/18/1933 19:00

# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc

In [ ]:
df2.iloc[:3]

      ColonneA ColonneB  ColonneC ColonneD         ColonneE
0       Ithaca      NaN  TRIANGLE       NY   6/1/1930 22:00
1  Willingboro      NaN     OTHER       NJ  6/30/1930 20:00
2      Holyoke      NaN      OVAL       CO  2/15/1931 14:00

# Mission 7

Achieve the same result as in mission 6 by using loc

In [ ]:
df2.loc[0:2]

      ColonneA ColonneB  ColonneC ColonneD         ColonneE
0       Ithaca      NaN  TRIANGLE       NY   6/1/1930 22:00
1  Willingboro      NaN     OTHER       NJ  6/30/1930 20:00
2      Holyoke      NaN      OVAL       CO  2/15/1931 14:00